# Generated by Django 3.1.1 on 2020-09-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
